[package]
name = "paks-api"
version.workspace = true
edition.workspace = true
description = "Paks Registry API client"

[dependencies]
paks-api-schema = { path = "../schema" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
reqwest.workspace = true
tokio.workspace = true
url.workspace = true
urlencoding = "2"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
